### PR TITLE
Update Dockerfile

### LINKED ISSUE #108: Timeout when fetching @my_deps
**Describe the bug**
After running `docker-compose up --build`, a timeout occurs when fetching `@my_deps`.

**To Reproduce**
1. Clone the repository
2. Add a `.env` file in the cloned repository.
3. Run `docker-compose up --build` 
4. Wait for building to reach stage of timing out while fetching `@my_deps`
5. See error

**Expected behavior**
`@my_deps` fetched successfully without timeout

**Desktop:**
 - OS: Ubuntu 20.04.2.0 LTS

### PR DESCRIPTION
**Pull request by codecakes**
fixes #108 https://github.com/Xcov19/covidX/issues/108

---
This change is [Reviewable](https://reviewable.io/reviews/xcov19/covidx/112)

### CODE REVIEW

**Comment by milan-tom** [comment]
I will build it locally and verify that it fixes the issue.

**Comment by milan-tom** [comment]
> I will build it locally and verify that it fixes the issue.

Still results in the same error:
```
ERROR: no such package '@my_deps//': pip_import failed:  (Timed out)
```

**Comment by codecakes** [comment]
> > I will build it locally and verify that it fixes the issue.
> 
> Still results in the same error:
> 
> ```
> ERROR: no such package '@my_deps//': pip_import failed:  (Timed out)
> ```

What happens when you do:
`docker run --rm -it --security-opt apparmor=unconfined codecakes/covidx_backend`

**Comment by codecakes** [comment]
> > I will build it locally and verify that it fixes the issue.
> 
> Still results in the same error:
> 
> ```
> ERROR: no such package '@my_deps//': pip_import failed:  (Timed out)
> ```

 @milan-tom fixes your issue; try now

**Comment by codecakes** [comment]
Gitpod builds successfully; There is some Gitpod container level issue; bug filed: https://github.com/gitpod-io/gitpod/issues/3632

**Pull request merged**
