### PR TITLE
Revert "Update pyopenssl and cryptography"

### PR DESCRIPTION
**Pull request by codecakes**
Reverts Xcov19/covidX#117

https://github.com/Xcov19/covidX/runs/2481887587?check_suite_focus=true

Add  --allow-unsafe

<a href="https://gitpod.io/#https://github.com/Xcov19/covidX/pull/120"></a>

---
This change is [Reviewable](https://reviewable.io/reviews/xcov19/covidx/120)

### CODE REVIEW

**Comment by xmunoz** [comment]
I see that the build is still failing.

**Review by xmunoz — COMMENTED** [review]
See above. Not sure this PR addresses the issue.

**Comment by codecakes** [comment]
> I see that the build is still failing.

See the build issue: https://github.com/Xcov19/covidX/runs/2481887587?check_suite_focus=true

Tis needs to be addressed in a different PR

**Comment by codecakes** [comment]
#121 fixes this issue.

**Pull request closed without merging**
